- name: Get composer
  shell: curl -sS https://getcomposer.org/installer | php

- name: Move composer to /usr/local/bin/
  shell: mv composer.phar /usr/local/bin/composer
  become: yes

- name: Update Composer
  shell: /usr/local/bin/composer config -g github-oauth.github.com {{ github_oauth_key }} 
  when: "{{ configure_composer_key | bool }}"
